### ISSUE TITLE
element not interactable

### ISSUE THREAD

**Issue by minscof** [simao-silva/noip-renewer#12]
I try this image simaofsilva/noip-renewer:3.9.1-slim-buster on a buster raspbian and I have an error. Maybe the login page changed ?

Thank you for your help

Opening browser
Login page
Traceback (most recent call last):
  File "//renew.py", line 48, in <module>
    browser.find_element_by_name("Login").click()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=88.0.4324.182)

**Comment by minscof** [comment]
I think the image, I used, was too old

I change for this image : simaofsilva/noip-renewer:debian

and I have another error

Opening browser
Traceback (most recent call last):
  File "//renew.py", line 41, in <module>
    browser = webdriver.Chrome(options=browserOptions)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by simao-silva** [comment]
The image with tag 3.9.1 is a year old so I do not recommend use it, so please use tag `debian` and update that from time to time. 
I have the image with tag `debian` running on a arm/v7 device without any issues. Are you running the right image for your processor's architecture? What is the output of `uname --m`?

**Comment by minscof** [comment]
The output if uname --m is  
armv7l

is debian tag the right image for my raspberry ?

**Comment by minscof** [comment]
Yes, it seems to be the right version, what can be wrong ?
REPOSITORY                 TAG       IMAGE ID       CREATED      SIZE
simaofsilva/noip-renewer   debian    bc1c130454d9   6 days ago   462MB

**Comment by simao-silva** [comment]
That seems alright. 
It can be a memory problem with the container exhausting the RAM and crashing. Have you check the Raspberry status while the container is running?

**Comment by minscof** [comment]
I didn't find some trouble with my raspberry. So I build my own image but I change bullseye by buster because my raspberry run with buster

And it works with this new image

My change :

FROM python:3.10.4-slim-buster@sha256:c2824bf9bdb9dbeed967df6805388e90e67439aae4934c02526d8ce5c29ae6d1

Could you upgrade your debian image to buster ?

I also use renew.py and not renew_legacy.py : I don't know why you keep a specific version for debian : maybe you can merge.

Thanks a lot

**Comment by simao-silva** [comment]
Your running in a container so it does not matter which version of Debian you are using on your Raspberry Pi. Still, going from bullseye to buster is a downgrade, not an upgrade.
I am still wondering how the current image does not work in your environment but I am glad you found a solution for your issue.
