### ISSUE TITLE
How to configure the frequency?

### ISSUE THREAD

**Issue by ni7ht** [simao-silva/noip-renewer#147]
docker run --rm will auto delete the when container run at once so i use option - --restart always and i found that it auto-starts in every  about 10 mins,the log below could prove it. Where could i set the start time? Thanks.

2024-03-07T05:12:57.089953096Z Opening browser
2024-03-07T05:12:57.090009305Z Login button not found within the specified timeout.
2024-03-07T05:26:05.956276357Z Opening browser
2024-03-07T05:26:05.956447733Z Login successful
2024-03-07T05:26:05.956459704Z Confirming hosts phase
2024-03-07T05:26:05.956469172Z Checking if host "example.ddns.net" needs confirmation
2024-03-07T05:26:05.956477900Z Error:  HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fee11a92120>, 'Connection to translate.google.com timed out. (connect timeout=None)'))
2024-03-07T05:26:05.956487824Z Logging off
2024-03-07T05:26:05.956493958Z 
2024-03-07T05:26:05.956502363Z 
2024-03-07T05:39:13.500413678Z Opening browser
2024-03-07T05:39:13.500470773Z Login successful
2024-03-07T05:39:13.500478550Z Confirming hosts phase
2024-03-07T05:39:13.500484982Z Checking if host "example.ddns.net" needs confirmation
2024-03-07T05:39:13.500492201Z Error:  HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb0a67789e0>, 'Connection to translate.google.com timed out. (connect timeout=None)'))
2024-03-07T05:39:13.500528672Z Logging off
2024-03-07T05:39:13.500538845Z 
2024-03-07T05:39:13.500545339Z 
2024-03-07T05:49:22.211397608Z Opening browser
2024-03-07T05:49:22.211464766Z Login successful
2024-03-07T05:49:22.211404763Z Traceback (most recent call last):
2024-03-07T05:49:22.211483100Z   File "/app/renew.py", line 120, in <module>
2024-03-07T05:49:22.211640428Z     browser.get(HOST_URL)
2024-03-07T05:49:22.211655793Z   File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
2024-03-07T05:49:22.211995529Z     self.execute(Command.GET, {"url": url})
2024-03-07T05:49:22.212091484Z   File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
2024-03-07T05:49:22.212332712Z     self.error_handler.check_response(response)
2024-03-07T05:49:22.212404707Z   File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-03-07T05:49:22.212653510Z     raise exception_class(message, screen, stacktrace)
2024-03-07T05:49:22.212780102Z selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 300000 ms
2024-03-07T05:49:22.212792311Z Stacktrace:
2024-03-07T05:49:22.212801459Z RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
2024-03-07T05:49:22.212833063Z WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
2024-03-07T05:49:22.212840943Z TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:723:5
2024-03-07T05:49:22.212847501Z bail@chrome://remote/content/marionette/sync.sys.mjs:211:19
2024-03-07T05:49:22.212856173Z 
2024-03-07T05:59:55.481543346Z Opening browser
2024-03-07T05:59:55.481602386Z Login successful
2024-03-07T05:59:55.481609925Z Confirming hosts phase
2024-03-07T05:59:55.481616040Z Checking if host "example.ddns.net" needs confirmation
2024-03-07T05:59:55.481622681Z Error:  HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f7aa369de20>, 'Connection to translate.google.com timed out. (connect timeout=None)'))
2024-03-07T05:59:55.481631822Z Logging off
2024-03-07T05:59:55.481640443Z 
2024-03-07T05:59:55.481648866Z 
2024-03-07T06:13:03.226728165Z Opening browser
2024-03-07T06:13:03.226790201Z Login successful
2024-03-07T06:13:03.226797650Z Confirming hosts phase
2024-03-07T06:13:03.226803589Z Checking if host "example.ddns.net" needs confirmation
2024-03-07T06:13:03.226811461Z Error:  HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f5246195e50>, 'Connection to translate.google.com timed out. (connect timeout=None)'))
2024-03-07T06:13:03.226821161Z Logging off
2024-03-07T06:13:03.226829461Z 
2024-03-07T06:13:03.226837799Z 
2024-03-07T06:26:13.553158492Z Opening browser
2024-03-07T06:26:13.553270682Z Login successful
2024-03-07T06:26:13.553280768Z Confirming hosts phase
2024-03-07T06:26:13.553287438Z Checking if host "example.ddns.net" needs confirmation
2024-03-07T06:26:13.553298411Z Error:  HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f1ef0b3e1b0>, 'Connection to translate.google.com timed out. (connect timeout=None)'))
2024-03-07T06:26:13.553310785Z Logging off
2024-03-07T06:26:13.553317011Z 
2024-03-07T06:26:13.553322505Z 
2024-03-07T06:32:51.338735834Z Opening browser
2024-03-07T06:32:51.338895543Z Login button not found within the specified timeout.
2024-03-07T06:42:53.795968823Z Opening browser
2024-03-07T06:42:53.796024562Z Login successful
2024-03-07T06:42:53.795969580Z Traceback (most recent call last):
2024-03-07T06:42:53.796040574Z   File "/app/renew.py", line 120, in <module>
2024-03-07T06:42:53.796190314Z     browser.get(HOST_URL)
2024-03-07T06:42:53.796272143Z   File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
2024-03-07T06:42:53.796505640Z     self.execute(Command.GET, {"url": url})
2024-03-07T06:42:53.796617774Z   File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
2024-03-07T06:42:53.796853781Z     self.error_handler.check_response(response)
2024-03-07T06:42:53.796949837Z   File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
2024-03-07T06:42:53.797193864Z     raise exception_class(message, screen, stacktrace)
2024-03-07T06:42:53.797311410Z selenium.common.exceptions.TimeoutException: Message: Navigation timed out after 300000 ms
2024-03-07T06:42:53.797323238Z Stacktrace:
2024-03-07T06:42:53.797332145Z RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
2024-03-07T06:42:53.797338906Z WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
2024-03-07T06:42:53.797345033Z TimeoutError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:723:5
2024-03-07T06:42:53.797350884Z bail@chrome://remote/content/marionette/sync.sys.mjs:211:19
2024-03-07T06:42:53.797356768Z 
2024-03-07T06:49:34.479709188Z Opening browser
2024-03-07T06:49:34.479861099Z Login button not found within the specified timeout.
2024-03-07T07:02:46.750639080Z Opening browser
2024-03-07T07:02:46.750695153Z Login successful
2024-03-07T07:02:46.750705257Z Confirming hosts phase
2024-03-07T07:02:46.750714358Z Checking if host "example.ddns.net" needs confirmation
2024-03-07T07:02:46.750722846Z Error:  HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /m?tl=en&sl=auto&q=Modify (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb954b56120>, 'Connection to translate.google.com timed out. (connect timeout=None)'))
2024-03-07T07:02:46.750732623Z Logging off
2024-03-07T07:02:46.750738853Z 
2024-03-07T07:02:46.750747248Z 
2024-03-07T07:09:23.645054581Z Opening browser
2024-03-07T07:09:23.645111955Z Login button not found within the specified timeout.
2024-03-07T07:13:08.662976240Z Opening browser
2024-03-07T07:13:08.663071707Z Could not login. Check if account is blocked.
2024-03-07T07:19:49.043996711Z Opening browser
2024-03-07T07:19:49.044058597Z Login button not found within the specified timeout.

**Comment by simao-silva** [comment]
Hi,
Did not understand what exactly you are asking. The renovation script starts as soon as the container starts. From the log attached, it seems you are having network issues. Did you check with other containers if this behaviour happens as well?

**Comment by ni7ht** [comment]
> Hi, Did not understand what exactly you are asking. The renovation script starts as soon as the container starts. From the log attached, it seems you are having network issues. Did you check with other containers if this behaviour happens as well?

Put the command in crontab, got it. My network is ok and google service is not reachable in some regions like where i located. That's why Login successful with translate.google.com  ConnectTimeoutError. I didn't found proxy or google translate disable option.

**Comment by simao-silva** [comment]
You did not find because there is no such option. I will try to patch the script in the meantime to accommodate that.

**Comment by simao-silva** [comment]
Option to disabled translation added in #161. It can be disabled by setting `TRANSLATE_ENABLED` environment variable to `false`.
