### ISSUE TITLE
session deleted because of page crash

### ISSUE THREAD

**Issue by homefefeld** [simao-silva/noip-renewer#17]
Hi there,

I'm trying to run the docker. my setup is an headless Debian 11.5. 
when I run the docker, I get the following error :

**>> sudo docker run --rm simaofsilva/noip-renewer:latest $EMAIL $PASSWORD**
Opening browser
Traceback (most recent call last):
  File "//renew.py", line 75, in <module>
    i.click()
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=102.0.5005.182)

**Comment by homefefeld** [comment]
it seems that I was not really headless.
the I ran 
   **systemctl set-default**
got back : 
   **graphical.target**

running :  
   **systemctl set-default multi-user** 
fixed the issue.
