### ISSUE TITLE
Could not login. Check if account is blocked.

### ISSUE THREAD

**Issue by Ivan-ggg** [simao-silva/noip-renewer#189]
Using user agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
Opening browser
Could not login. Check if account is blocked.

I've been using it for renewals for several years now, thanks to this program! But in the last couple of days, I suddenly realized that I can't renew. I tried to log in to my account and found that I had to enter the verification code that was sent to my email address to log in to my account, and I couldn't close it. Can this program be improved please? I think there are two ways to successfully log in to the account, one is to turn on two-step verification and calculate the two-step verification code via the parameter Key to log in to the account, and the other is to set up mail forwarding to get the two-step verification code via a service like mailparser to log in to the account.

**Comment by Kucharskov** [comment]
As far as i understand ita issued by new noip browser verification by mail code. I noticed today on my mailbox that i got code exact time when script was executed.

Technically it should be resolved by switch like "--authenticate" ran once which will prompt for that 6digit key from mail and will use "remember this browser" option.

**Comment by ray1025** [comment]
I've encountered the same issue. Regarding the above, I suggest using a two-step verification key for automatic login.

**Comment by CheckeredFlag** [comment]
> I've encountered the same issue. Regarding the above, I suggest using a two-step verification key for automatic login.

Agreed.  Adding support for TOTP may be the best solution.

**Comment by ray1025** [comment]
Perhaps you could achieve the desired functionality using the pyotp library?

**Comment by rpanchon** [comment]
I’ve found the same issue. The no-ip web ask for the security code.

**Comment by simao-silva** [comment]
#194 adds support for 2FA but it does not support the email code request. As far as I could tell, this happens from time to time thus difficult to reproduce. From what I understood, if you want to avoid the code to be sent via email, enable the 2FA from NOIP and set the `NO_IP_TOTP_KEY` variable or paste it when this script prompt for it.

**Comment by rpanchon** [comment]
After supports 2FA the tool is returning an error.
```bash
docker.io/simaofsilva/noip-renewer:latest
Using user agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 14.1; rv:109.0) Gecko/20100101 Firefox/121.0"
Opening browser
Traceback (most recent call last):
  File "/app/renew.py", line 146, in <module>
    totp_input.send_keys(totp.now())
                         ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pyotp/totp.py", line 64, in now
    return self.generate_otp(self.timecode(datetime.datetime.now()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pyotp/otp.py", line 35, in generate_otp
    hasher = hmac.new(self.byte_secret(), self.int_to_bytestring(input), self.digest)
                      ^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/pyotp/otp.py", line 52, in byte_secret
    return base64.b32decode(secret, casefold=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/base64.py", line 254, in b32decode
    return _b32decode(_b32alphabet, s, casefold, map01)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/base64.py", line 236, in _b32decode
    raise binascii.Error('Non-base32 digit found') from None
binascii.Error: Non-base32 digit found
```

**Comment by ray1025** [comment]
@rpanchon  double check your 2fa secret, that error usually means you put the wrong one

**Comment by rpanchon** [comment]
Tahnk you! you are right, i had the Two-Factor Authentication enabled.
