### ISSUE TITLE
 Message: unknown error: session deleted because of page crash

### ISSUE THREAD

**Issue by ogizhelev** [simao-silva/noip-renewer#21]
Often there is an error with simaofsilva/noip-renewer:alpine image 

Traceback (most recent call last):
  File "//renew.py", line 75, in <module>
    i.click()
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
Opening browser
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/root/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=102.0.5005.182)

Is I guess might be worth adding some sleep()  L72-L76 as I assume it takes more time to load the page

**Comment by simao-silva** [comment]
Hi,
This error is related to #18 . I believe I corrected this error already so try pulling the image again.

**Comment by ogizhelev** [comment]
Status: Downloaded newer image for simaofsilva/noip-renewer:alpine
Opening browser
Login successful
Confirming hosts phase
0 hosts confirmed
Finished
Logging off
