### ISSUE TITLE
TOTP problem with latest image

### ISSUE THREAD

**Issue by Kucharskov** [simao-silva/noip-renewer#225]
Hi all! I have issue using noip-renewer,
Command: `docker run --rm --env NO_IP_USERNAME="VALUE" --env NO_IP_PASSWORD="VALUE" --env NO_IP_TOTP_KEY="VALUE" simaofsilva/noip-renewer`
Output:
```
Using user agent "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:109.0) Gecko/20100101 Firefox/121.0"
Opening browser
Traceback (most recent call last):
  File "/app/renew.py", line 146, in <module>
    totp_input.send_keys(totp.now())
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 231, in send_keys
    self._execute(
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <input id="challenge_code" name="challenge_code" type="hidden"> is not reachable by keyboard
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:353:5
webdriverSendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:668:13
interaction.sendKeysToElement@chrome://remote/content/marionette/interaction.sys.mjs:642:11
sendKeysToElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:540:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:150:31
```

According to thread https://github.com/simao-silva/noip-renewer/issues/221#issuecomment-2143813417 i already managed to fixed issue using `simaofsilva/noip-renewer:c01467b-alpine` image, but i think that it should be fixed in latest image also :)

Regards!

**Comment by ray1025** [comment]
Before running `docker run`, did you execute `docker pull simaofsilva/noip-renewer`?

**Comment by Kucharskov** [comment]
Holy moly i forgot that! I added to crontab just `` --pull=missing`` in docker run and it fixes issues :)
