### ISSUE TITLE
Build throwing python error 

### ISSUE THREAD

**Issue by Kane-LName** [simao-silva/noip-renewer#25]
When launching docker it throws an error with python 3.11. Originally thought NO-IPs MFA would be an issue however it persists with MFA both enabled and disabled

Shell
```sh
docker pull simaofsilva/noip-renewer:debian
EMAIL='[snip]'
PASSWORD='[snip]'
docker run --rm -it simaofsilva/noip-renewer:debian $EMAIL $PASSWORD
```
Output:
```
Status: Image is up to date for simaofsilva/noip-renewer:debian
docker.io/simaofsilva/noip-renewer:debian
Opening browser
```
Throws:
```python
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/urllib3/connection.py", line 1                 74, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/urllib3/util/connection.py", l                 ine 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", li                 ne 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", li                 ne 386, in _make_request
    self._validate_conn(conn)
  File "/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", li                 ne 1042, in _validate_conn
    conn.connect()
  File "/root/.local/lib/python3.11/site-packages/urllib3/connection.py", line 3                 58, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/urllib3/connection.py", line 1                 86, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection objec                 t at 0x7f6b786f9a90>: Failed to establish a new connection: [Errno -3] Temporary                  failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/requests/adapters.py", line 48                 9, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", li                 ne 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/urllib3/util/retry.py", line 5                 92, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='jnrbsn.github.io', p                 ort=443): Max retries exceeded with url: /user-agents/user-agents.json (Caused b                 y NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b786f9a                 90>: Failed to establish a new connection: [Errno -3] Temporary failure in name                  resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//renew.py", line 58, in <module>
    browserOptions.add_argument("user-agent=" + str(get_user_agent()))
                                                    ^^^^^^^^^^^^^^^^
  File "//renew.py", line 31, in get_user_agent
    r = requests.get(url="https://jnrbsn.github.io/user-agents/user-agents.json"                 )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 ^
  File "/root/.local/lib/python3.11/site-packages/requests/api.py", line 73, in                  get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/api.py", line 59, in                  request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/sessions.py", line 58                 7, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/sessions.py", line 70                 1, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/lib/python3.11/site-packages/requests/adapters.py", line 56                 5, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='jnrbsn.github.io'                 , port=443): Max retries exceeded with url: /user-agents/user-agents.json (Cause                 d by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6b786                 f9a90>: Failed to establish a new connection: [Errno -3] Temporary failure in na                 me resolution'))

```

**Comment by simao-silva** [comment]
That seems to be a temporary connection error. Have you tried run it again? I ran it, just in case, and worked as expected.
