### ISSUE TITLE
The new version has issues.

### ISSUE THREAD

**Issue by ray1025** [simao-silva/noip-renewer#37]
Digest: sha256:b1bc07efc69aa42ba526532ac56941826e5f6cb7bce571dab88f386ab73aafc0
Status: Downloaded newer image for simaofsilva/noip-renewer:debian
Traceback (most recent call last):
Opening browser
  File "//renew.py", line [62](https://github.com/ray1025/automation/actions/runs/6427062677/job/17452151857#step:2:63), in <module>
    browser = webdriver.Firefox(options=browser_options, service=service)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line [67](https://github.com/ray1025/automation/actions/runs/6427062677/job/17452151857#step:2:68), in __init__
    super().__init__(command_executor=executor, options=options)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
    self.start_session(capabilities)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
    self.error_handler.check_response(response)
  File "/opt/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by mikeyounge** [comment]
I am seeing the same error on all the tags.

**Comment by simao-silva** [comment]
I am aware of these recent issues. Please try again with tags `4286f44-alpine` or `4286f44-debian`.

**Comment by ray1025** [comment]
@simao-silva 
"4286f44-debian" is now working fine. Thank you for your hard work!

**Comment by simao-silva** [comment]
That is great. Thank you for the feedback.

**Comment by mikeyounge** [comment]
Tested the Debian tag and it worked great. Responses were as expected for a host that had nothing to confirm. Thanks. Should I keep the tag or go back to latest?On Oct 7, 2023, at 10:58 AM, Simão Silva ***@***.***> wrote:﻿
Closed #37 as completed.
