### ISSUE TITLE
not working this month

### ISSUE THREAD

**Issue by terry778778** [simao-silva/noip-renewer#4]
It worked perfectly last month, nothing has changed.

Opening browser
Traceback (most recent call last):
  File "//renew.py", line 47, in <module>
    browser.find_element_by_name("Login").click()
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=86.0.4240.111)

**Comment by simao-silva** [comment]
Hi,

Some of the source code of NO-IP has changed and the login button was one of those changes. I've updated the script and things should by working for you now. Can you check?

**Comment by terry778778** [comment]
> Hi,
> 
> 
> 
> Some of the source code of NO-IP has changed and the login button was one of those changes. I've updated the script and things should by working for you now. Can you check? 

thanks buddy, i will check it right now

**Comment by terry778778** [comment]
> Hi,
> 
> 
> 
> Some of the source code of NO-IP has changed and the login button was one of those changes. I've updated the script and things should by working for you now. Can you check? 

It works! Thanks!
